name: persistent-clickhouse
version: 0.1.0.0
github: "githubuser/persistent-clickhouse"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/persistent-clickhouse#readme>

dependencies:
  - base >= 4.7 && < 5
  - persistent
  - bytestring
  - clickhouse-driver
  - text
  - vector
  - exceptions
  - conduit
  - cassava
  - monad-logger
  - mtl
  - time
  - uuid
  - containers
  - template-haskell
  - optics >= 0.4
  - tz
  - PyF
  - pretty-simple 
  - aeson
  - cereal

default-extensions:
  - OverloadedStrings
  - TypeOperators
  - TypeApplications
  - TypeFamilies
  - DataKinds
  - FunctionalDependencies
  - LambdaCase
  - NamedFieldPuns
  - ViewPatterns
  - PatternSynonyms
  - GADTs
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedLists
  - BangPatterns
  - DuplicateRecordFields
  - PolyKinds
  - FlexibleContexts
  - FlexibleInstances

library:
  source-dirs: src

tests:
  persistent-clickhouse-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - persistent-clickhouse
